# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

target 'PokeMatch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PokeMatch
	pod 'Firebase/Core'
	pod 'Fabric', '~> 1.9.0'
	pod 'Crashlytics', '~> 3.12.0'
	pod 'Firebase/Performance'
	pod 'SwiftyGif', '~> 4.2'

  target 'PokeMatchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PokeMatchUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
